name: build_APP
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.8.x"
      - run: flutter pub get
      #- run: flutter test
      - run: gradle -v
      - run: flutter build apk

