name: build_APP
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  flutter_analysis:
    name: Test, Build and Release apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.8.x"
      - run: flutter pub get
      #- run: flutter test
  build_appbundle:
    name: Build Flutter for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.8.x"
      - run: flutter build appbundle
      - name: actions/upload-artifact@v2
        with:
          name: apk-build
          path: build/app/outputs/apk/release
    